### ISSUE TITLE
Warning models.W042 on both tables

### ISSUE THREAD

**Issue by ClearSky0** [akjasim/cb_dj_select2#3]
Not a big deal but the project gives the following warnings when running;

```
WARNINGS:
core.Entry: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.        
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the CoreConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
core.Language: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.     
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the CoreConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'
```

I chose to add a pk;

models.py
```

from django.db import models

# Create your models here.


class Language(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=56)

    def __str__(self):
        return self.title


class Entry(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=124)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, verbose_name="Favourite Language")

    def __str__(self):
        return self.name
```
